// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChunkFormsController from "./chunk_forms_controller"
application.register("chunk-forms", ChunkFormsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PokItemsController from "./pok_items_controller"
application.register("pok-items", PokItemsController)
